version: "3.8"

services:
  app:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "16379:6379"